import type { BlueprintDocInput } from "./schema.js";

/**
 * Built-in Tier-1 catalog (FR-043). Data-only documents validated at boot.
 * Static resolvers carry versions inline so the panel works offline and never
 * silently falls back to stale lists.
 */
export const BUILTIN_BLUEPRINTS: BlueprintDocInput[] = [
  {
    schemaVersion: 1,
    slug: "vanilla",
    name: "Minecraft: Java Edition (Vanilla)",
    category: "minecraft-java",
    description: "Official Mojang vanilla server, fetched from the Mojang manifest.",
    docsUrl: "https://www.minecraft.net/download/server",
    tag: "v1",
    requirements: { engine: "process", arch: ["amd64", "arm64"], hostOs: ["linux", "windows"] },
    resolvers: [{ id: "mojang", kind: "mojang-manifest" }],
    versions: {
      javaMapping: [
        { mcRange: ">=1.21.9", image: "ghcr.io/renom/java:25" },
        { mcRange: "1.20.5 - 1.21.x", image: "ghcr.io/renom/java:21" },
        { mcRange: "1.18 - 1.20.4", image: "ghcr.io/renom/java:17" },
      ],
    },
    image: "ghcr.io/renom/java:21",
    install: [
      { op: "fetch-vanilla", version: "{mcVersion}" },
      { op: "eula-accept" },
      {
        op: "writefile",
        path: "server.properties",
        contentTemplate:
          "motd={MOTD}\nserver-port={allocation.port}\nenforce-secure-profile=false\n",
      },
    ],
    run: {
      command: ["java", "-Xms{initMemory}M", "-Xmx{maxMemory}M", "-jar", "server.jar", "nogui"],
      workdir: "/data",
      stop: { kind: "console", command: "stop", timeoutSec: 30 },
      envCanon: {},
    },
    variables: [
      {
        key: "mcVersion",
        label: "Minecraft version",
        type: "string",
        default: "latest",
        userViewable: true,
        userEditable: true,
        internal: false,
      },
      {
        key: "MOTD",
        label: "Message of the day",
        type: "string",
        default: "A Renom server",
        userViewable: true,
        userEditable: true,
        internal: false,
        rules: { maxLength: 64 },
      },
      {
        key: "maxMemory",
        label: "Max RAM (MB)",
        type: "integer",
        default: 2048,
        userViewable: true,
        userEditable: true,
        internal: false,
        rules: { min: 512, max: 32768 },
      },
      {
        key: "initMemory",
        label: "Initial RAM (MB)",
        type: "integer",
        default: 1024,
        userViewable: false,
        userEditable: false,
        internal: true,
        rules: { min: 512 },
      },
    ],
    ports: [
      { name: "game", protocol: "tcp", default: 25565, required: true },
      { name: "query", protocol: "udp", default: 25565, required: false },
    ],
    healthcheck: { kind: "tcp", port: "game", timeoutSec: 10, startPeriodSec: 90 },
    backupPolicy: { consistency: "stopped" },
    update: { strategy: "resolver-refetch", onStart: true },
    fileDenylist: [".renom/**"],
    features: ["eula"],
  },
  {
    schemaVersion: 1,
    slug: "paper",
    name: "Paper",
    category: "minecraft-java",
    description: "High-performance Minecraft server (PaperMC), resolved via PaperMC Fill v3.",
    docsUrl: "https://papermc.io",
    tag: "v1",
    requirements: { engine: "process", arch: ["amd64", "arm64"], hostOs: ["linux", "windows"] },
    resolvers: [{ id: "paper-fill", kind: "papermc-fill", project: "paper" }],
    versions: {
      javaMapping: [
        { mcRange: ">=1.21.9", image: "ghcr.io/renom/java:25" },
        { mcRange: "1.20.5 - 1.21.x", image: "ghcr.io/renom/java:21" },
        { mcRange: "1.18 - 1.20.4", image: "ghcr.io/renom/java:17" },
      ],
    },
    image: "ghcr.io/renom/java:21",
    install: [
      { op: "fetch-paper", version: "{mcVersion}" },
      { op: "eula-accept" },
      {
        op: "writefile",
        path: "server.properties",
        contentTemplate: "motd={MOTD}\nserver-port={allocation.port}\n",
      },
    ],
    run: {
      command: ["java", "-Xms{initMemory}M", "-Xmx{maxMemory}M", "-jar", "paper.jar", "nogui"],
      workdir: "/data",
      stop: { kind: "console", command: "stop", timeoutSec: 30 },
      envCanon: {},
    },
    variables: [
      {
        key: "mcVersion",
        label: "Minecraft version",
        type: "string",
        default: "latest",
        userViewable: true,
        userEditable: true,
        internal: false,
      },
      {
        key: "MOTD",
        label: "Message of the day",
        type: "string",
        default: "A Renom server",
        userViewable: true,
        userEditable: true,
        internal: false,
        rules: { maxLength: 64 },
      },
      {
        key: "maxMemory",
        label: "Max RAM (MB)",
        type: "integer",
        default: 2048,
        userViewable: true,
        userEditable: true,
        internal: false,
        rules: { min: 512, max: 32768 },
      },
      {
        key: "initMemory",
        label: "Initial RAM (MB)",
        type: "integer",
        default: 1024,
        userViewable: false,
        userEditable: false,
        internal: true,
        rules: { min: 512 },
      },
    ],
    ports: [{ name: "game", protocol: "tcp", default: 25565, required: true }],
    healthcheck: { kind: "tcp", port: "game", timeoutSec: 10, startPeriodSec: 90 },
    backupPolicy: { consistency: "stopped" },
    update: { strategy: "resolver-refetch", onStart: true },
    fileDenylist: [".renom/**"],
    features: ["eula"],
  },
  {
    schemaVersion: 1,
    slug: "bedrock-bds",
    name: "Minecraft: Bedrock Dedicated Server",
    category: "minecraft-bedrock",
    description: "Official Bedrock Dedicated Server from the Mojang BDS registry.",
    docsUrl: "https://www.minecraft.net/en-us/download/server/bedrock",
    tag: "v1",
    requirements: { engine: "docker", arch: ["amd64"], hostOs: ["linux"] },
    resolvers: [{ id: "bds", kind: "bds-registry" }],
    versions: {},
    image: "ghcr.io/renom/bds:latest",
    install: [
      { op: "fetch-bds", channel: "stable" },
      { op: "chmod", path: "bedrock_server", mode: 493 },
      {
        op: "writefile",
        path: "server.properties",
        contentTemplate:
          "server-name={SERVER_NAME}\nserver-port={allocation.port}\nserver-portv6=0\nonline-mode=true\n",
      },
    ],
    run: {
      command: ["./bedrock_server"],
      workdir: "/data",
      stop: { kind: "console", command: "stop", timeoutSec: 30 },
      envCanon: { SERVER_NAME: "{name}" },
    },
    variables: [
      {
        key: "SERVER_NAME",
        label: "Server name",
        type: "string",
        default: "Renom Bedrock",
        userViewable: true,
        userEditable: true,
        internal: false,
        rules: { maxLength: 48 },
      },
    ],
    ports: [
      { name: "game", protocol: "udp", default: 19132, required: true },
      { name: "gamev6", protocol: "udp", default: 19133, required: false },
    ],
    healthcheck: { kind: "tcp", port: "game", timeoutSec: 10, startPeriodSec: 60 },
    backupPolicy: { consistency: "stopped" },
    update: { strategy: "resolver-refetch", onStart: false },
    fileDenylist: [".renom/**"],
    features: [],
  },
  {
    schemaVersion: 1,
    slug: "generic-java",
    name: "Generic Java server (custom JAR)",
    category: "generic-runtime",
    description: "Run any Java jar you upload. You manage updates.",
    tag: "v1",
    requirements: { engine: "docker", arch: ["amd64", "arm64"], hostOs: ["linux"] },
    resolvers: [],
    versions: {},
    image: "ghcr.io/renom/java:21",
    install: [
      {
        op: "writefile",
        path: "server.properties",
        contentTemplate: "server-port={allocation.port}\n",
      },
    ],
    run: {
      command: ["java", "-Xms{initMemory}M", "-Xmx{maxMemory}M", "-jar", "{jarName}", "nogui"],
      workdir: "/data",
      stop: { kind: "console", command: "stop", timeoutSec: 30 },
      envCanon: {},
    },
    variables: [
      {
        key: "jarName",
        label: "Jar filename",
        type: "string",
        default: "server.jar",
        userViewable: true,
        userEditable: true,
        internal: false,
        rules: { pattern: "^[A-Za-z0-9._-]+\\.jar$" },
      },
      {
        key: "maxMemory",
        label: "Max RAM (MB)",
        type: "integer",
        default: 2048,
        userViewable: true,
        userEditable: true,
        internal: false,
        rules: { min: 512, max: 32768 },
      },
      {
        key: "initMemory",
        label: "Initial RAM (MB)",
        type: "integer",
        default: 1024,
        userViewable: false,
        userEditable: false,
        internal: true,
        rules: { min: 512 },
      },
    ],
    ports: [{ name: "game", protocol: "tcp", default: 25565, required: true }],
    healthcheck: { kind: "none", timeoutSec: 10, startPeriodSec: 90 },
    backupPolicy: { consistency: "best-effort" },
    update: { strategy: "none", onStart: false },
    fileDenylist: [".renom/**"],
    features: [],
  },
  {
    schemaVersion: 1,
    slug: "purpur",
    name: "Purpur",
    category: "minecraft-java",
    description: "Purpur — Paper fork with extra gameplay configuration, fetched from PurpurMC.",
    docsUrl: "https://purpurmc.org",
    tag: "v1",
    requirements: { engine: "process", arch: ["amd64", "arm64"], hostOs: ["linux", "windows"] },
    resolvers: [{ id: "purpur", kind: "purpur-v2", project: "purpur" }],
    versions: {},
    image: "ghcr.io/renom/java:21",
    install: [
      { op: "fetch-purpur", version: "{mcVersion}" },
      { op: "eula-accept" },
      { op: "writefile", path: "server.properties", contentTemplate: "motd={MOTD}\nserver-port={allocation.port}\nenforce-secure-profile=false\n" },
    ],
    run: {
      command: ["java", "-Xms{initMemory}M", "-Xmx{maxMemory}M", "-jar", "purpur.jar", "nogui"],
      workdir: "/data",
      stop: { kind: "console", command: "stop", timeoutSec: 30 },
      envCanon: {},
    },
    variables: [
      { key: "mcVersion", label: "Minecraft version", type: "string", default: "latest", userViewable: true, userEditable: true, internal: false },
      { key: "MOTD", label: "Message of the day", type: "string", default: "A Renom server", userViewable: true, userEditable: true, internal: false, rules: { maxLength: 64 } },
      { key: "maxMemory", label: "Max RAM (MB)", type: "integer", default: 2048, userViewable: true, userEditable: true, internal: false, rules: { min: 512, max: 32768 } },
      { key: "initMemory", label: "Initial RAM (MB)", type: "integer", default: 1024, userViewable: false, userEditable: false, internal: true, rules: { min: 512 } },
    ],
    ports: [{ name: "game", protocol: "tcp", default: 25565, required: true }],
    healthcheck: { kind: "tcp", port: "game", timeoutSec: 10, startPeriodSec: 90 },
    backupPolicy: { consistency: "stopped" },
    update: { strategy: "resolver-refetch", onStart: true },
    fileDenylist: [".renom/**"],
    features: ["eula"],
  },
  {
    schemaVersion: 1,
    slug: "fabric",
    name: "Fabric",
    category: "minecraft-java",
    description: "Fabric mod loader. Boots under Docker; local installs wire up next.",
    docsUrl: "https://fabricmc.net",
    tag: "v1",
    requirements: { engine: "docker", arch: ["amd64", "arm64"], hostOs: ["linux"] },
    resolvers: [{ id: "fabric-meta", kind: "fabric-meta" }],
    versions: {},
    image: "ghcr.io/renom/java:21",
    install: [{ op: "fetch-fabric", mcVersion: "{mcVersion}" }],
    run: {
      command: ["java", "-Xms{initMemory}M", "-Xmx{maxMemory}M", "-jar", "fabric-server-launch.jar", "nogui"],
      workdir: "/data",
      stop: { kind: "console", command: "stop", timeoutSec: 30 },
      envCanon: {},
    },
    variables: [
      { key: "mcVersion", label: "Minecraft version", type: "string", default: "latest", userViewable: true, userEditable: true, internal: false },
      { key: "maxMemory", label: "Max RAM (MB)", type: "integer", default: 2048, userViewable: true, userEditable: true, internal: false, rules: { min: 512, max: 32768 } },
      { key: "initMemory", label: "Initial RAM (MB)", type: "integer", default: 1024, userViewable: false, userEditable: false, internal: true, rules: { min: 512 } },
    ],
    ports: [{ name: "game", protocol: "tcp", default: 25565, required: true }],
    healthcheck: { kind: "tcp", port: "game", timeoutSec: 10, startPeriodSec: 90 },
    backupPolicy: { consistency: "stopped" },
    update: { strategy: "resolver-refetch", onStart: true },
    fileDenylist: [".renom/**"],
    features: ["eula"],
  },
  {
    schemaVersion: 1,
    slug: "forge",
    name: "Forge",
    category: "minecraft-java",
    description: "Minecraft Forge mod loader. Boots under Docker; local installs wire up next.",
    docsUrl: "https://minecraftforge.net",
    tag: "v1",
    requirements: { engine: "docker", arch: ["amd64", "arm64"], hostOs: ["linux"] },
    resolvers: [{ id: "forge", kind: "forge-promotions" }],
    versions: {},
    image: "ghcr.io/renom/java:21",
    install: [{ op: "fetch-forge", mcVersion: "{mcVersion}" }],
    run: {
      command: ["java", "-Xms{initMemory}M", "-Xmx{maxMemory}M", "@user_jvm_args.txt", "@libraries/net/minecraftforge/forge/{mcVersion}-forge-args.txt", "nogui"],
      workdir: "/data",
      stop: { kind: "console", command: "stop", timeoutSec: 30 },
      envCanon: {},
    },
    variables: [
      { key: "mcVersion", label: "Minecraft version", type: "string", default: "latest", userViewable: true, userEditable: true, internal: false },
      { key: "maxMemory", label: "Max RAM (MB)", type: "integer", default: 2048, userViewable: true, userEditable: true, internal: false, rules: { min: 512, max: 32768 } },
      { key: "initMemory", label: "Initial RAM (MB)", type: "integer", default: 1024, userViewable: false, userEditable: false, internal: true, rules: { min: 512 } },
    ],
    ports: [{ name: "game", protocol: "tcp", default: 25565, required: true }],
    healthcheck: { kind: "tcp", port: "game", timeoutSec: 10, startPeriodSec: 90 },
    backupPolicy: { consistency: "stopped" },
    update: { strategy: "resolver-refetch", onStart: true },
    fileDenylist: [".renom/**"],
    features: ["eula"],
  },
  {
    schemaVersion: 1,
    slug: "generic-nodejs",
    name: "Generic Node.js app",
    category: "generic-runtime",
    description: "Run a Node.js JavaScript entrypoint.",
    tag: "v1",
    requirements: { engine: "docker", arch: ["amd64", "arm64"], hostOs: ["linux"] },
    resolvers: [],
    versions: {},
    image: "ghcr.io/renom/node:22",
    install: [{ op: "mkdir", path: "app" }],
    run: {
      command: ["node", "{entryFile}"],
      workdir: "/data/app",
      stop: { kind: "signal", signal: "SIGTERM", timeoutSec: 15 },
      envCanon: {},
    },
    variables: [
      {
        key: "entryFile",
        label: "Entry file",
        type: "string",
        default: "index.js",
        userViewable: true,
        userEditable: true,
        internal: false,
        rules: { pattern: "^[A-Za-z0-9._/-]+\\.(m|c)?js$" },
      },
    ],
    ports: [{ name: "app", protocol: "tcp", default: 3000, required: false }],
    healthcheck: { kind: "none", timeoutSec: 10, startPeriodSec: 90 },
    backupPolicy: { consistency: "best-effort" },
    update: { strategy: "none", onStart: false },
    fileDenylist: [".renom/**"],
    features: [],
  },
  {
    schemaVersion: 1,
    slug: "generic-python",
    name: "Generic Python app",
    category: "generic-runtime",
    description: "Run a Python entrypoint with Python 3.12.",
    tag: "v1",
    requirements: { engine: "docker", arch: ["amd64", "arm64"], hostOs: ["linux"] },
    resolvers: [],
    versions: {},
    image: "ghcr.io/renom/python:3.12",
    install: [{ op: "mkdir", path: "app" }],
    run: {
      command: ["python", "-u", "{entryFile}"],
      workdir: "/data/app",
      stop: { kind: "signal", signal: "SIGTERM", timeoutSec: 15 },
      envCanon: {},
    },
    variables: [
      {
        key: "entryFile",
        label: "Entry file",
        type: "string",
        default: "main.py",
        userViewable: true,
        userEditable: true,
        internal: false,
        rules: { pattern: "^[A-Za-z0-9._/-]+\\.py$" },
      },
    ],
    ports: [{ name: "app", protocol: "tcp", default: 8000, required: false }],
    healthcheck: { kind: "none", timeoutSec: 10, startPeriodSec: 90 },
    backupPolicy: { consistency: "best-effort" },
    update: { strategy: "none", onStart: false },
    fileDenylist: [".renom/**"],
    features: [],
  },
];

/** A tiny static resolver used by tests and offline installs (never network-dependent). */
export const STATIC_TEST_VERSIONS = ["1.21.1", "1.21.8", "1.26.2"];
