import type { BlueprintDocInput } from "./schema.js";

/**
 * Built-in Tier-1 catalog (FR-043). Data-only documents validated at boot.
 * Static resolvers carry versions inline so the panel works offline and never
 * silently falls back to stale lists.
 */
export const BUILTIN_BLUEPRINTS: BlueprintDocInput[] = [
  {
    schemaVersion: 1,
    slug: "vanilla",
    name: "Minecraft: Java Edition (Vanilla)",
    category: "minecraft-java",
    description: "Official Mojang vanilla server, fetched from the Mojang manifest.",
    docsUrl: "https://www.minecraft.net/download/server",
    tag: "v1",
    requirements: { engine: "process", arch: ["amd64", "arm64"], hostOs: ["linux", "windows"] },
    resolvers: [{ id: "mojang", kind: "mojang-manifest" }],
    versions: {
      javaMapping: [
        { mcRange: ">=1.21.9", image: "ghcr.io/renom/java:25" },
        { mcRange: "1.20.5 - 1.21.x", image: "ghcr.io/renom/java:21" },
        { mcRange: "1.18 - 1.20.4", image: "ghcr.io/renom/java:17" },
      ],
    },
    image: "ghcr.io/renom/java:21",
    install: [
      { op: "fetch-vanilla", version: "{mcVersion}" },
      { op: "eula-accept" },
      {
        op: "writefile",
        path: "server.properties",
        contentTemplate:
          "motd={MOTD}\nserver-port={allocation.port}\nenforce-secure-profile=false\n",
      },
    ],
    run: {
      command: ["java", "-Xms{initMemory}M", "-Xmx{maxMemory}M", "-jar", "server.jar", "nogui"],
      workdir: "/data",
      stop: { kind: "console", command: "stop", timeoutSec: 30 },
      envCanon: {},
    },
    variables: [
      {
        key: "mcVersion",
        label: "Minecraft version",
        type: "string",
        default: "latest",
        userViewable: true,
        userEditable: true,
        internal: false,
      },
      {
        key: "MOTD",
        label: "Message of the day",
        type: "string",
        default: "A Renom server",
        userViewable: true,
        userEditable: true,
        internal: false,
        rules: { maxLength: 64 },
      },
      {
        key: "maxMemory",
        label: "Max RAM (MB)",
        type: "integer",
        default: 2048,
        userViewable: true,
        userEditable: true,
        internal: false,
        rules: { min: 512, max: 32768 },
      },
      {
        key: "initMemory",
        label: "Initial RAM (MB)",
        type: "integer",
        default: 1024,
        userViewable: false,
        userEditable: false,
        internal: true,
        rules: { min: 512 },
      },
    ],
    ports: [
      { name: "game", protocol: "tcp", default: 25565, required: true },
      { name: "query", protocol: "udp", default: 25565, required: false },
    ],
    healthcheck: { kind: "tcp", port: "game", timeoutSec: 10, startPeriodSec: 90 },
    backupPolicy: { consistency: "stopped" },
    update: { strategy: "resolver-refetch", onStart: true },
    fileDenylist: [".renom/**"],
    features: ["eula"],
  },
  {
    schemaVersion: 1,
    slug: "paper",
    name: "Paper",
    category: "minecraft-java",
    description: "High-performance Minecraft server (PaperMC), resolved via PaperMC Fill v3.",
    docsUrl: "https://papermc.io",
    tag: "v1",
    requirements: { engine: "process", arch: ["amd64", "arm64"], hostOs: ["linux", "windows"] },
    resolvers: [{ id: "paper-fill", kind: "papermc-fill", project: "paper" }],
    versions: {
      javaMapping: [
        { mcRange: ">=1.21.9", image: "ghcr.io/renom/java:25" },
        { mcRange: "1.20.5 - 1.21.x", image: "ghcr.io/renom/java:21" },
        { mcRange: "1.18 - 1.20.4", image: "ghcr.io/renom/java:17" },
      ],
    },
    image: "ghcr.io/renom/java:21",
    install: [
      { op: "fetch-paper", version: "{mcVersion}" },
      { op: "eula-accept" },
      {
        op: "writefile",
        path: "server.properties",
        contentTemplate: "motd={MOTD}\nserver-port={allocation.port}\n",
      },
    ],
    run: {
      command: ["java", "-Xms{initMemory}M", "-Xmx{maxMemory}M", "-jar", "paper.jar", "nogui"],
      workdir: "/data",
      stop: { kind: "console", command: "stop", timeoutSec: 30 },
      envCanon: {},
    },
    variables: [
      {
        key: "mcVersion",
        label: "Minecraft version",
        type: "string",
        default: "latest",
        userViewable: true,
        userEditable: true,
        internal: false,
      },
      {
        key: "MOTD",
        label: "Message of the day",
        type: "string",
        default: "A Renom server",
        userViewable: true,
        userEditable: true,
        internal: false,
        rules: { maxLength: 64 },
      },
      {
        key: "maxMemory",
        label: "Max RAM (MB)",
        type: "integer",
        default: 2048,
        userViewable: true,
        userEditable: true,
        internal: false,
        rules: { min: 512, max: 32768 },
      },
      {
        key: "initMemory",
        label: "Initial RAM (MB)",
        type: "integer",
        default: 1024,
        userViewable: false,
        userEditable: false,
        internal: true,
        rules: { min: 512 },
      },
    ],
    ports: [{ name: "game", protocol: "tcp", default: 25565, required: true }],
    healthcheck: { kind: "tcp", port: "game", timeoutSec: 10, startPeriodSec: 90 },
    backupPolicy: { consistency: "stopped" },
    update: { strategy: "resolver-refetch", onStart: true },
    fileDenylist: [".renom/**"],
    features: ["eula"],
  },
  {
    schemaVersion: 1,
    slug: "purpur",
    name: "Purpur",
    category: "minecraft-java",
    description: "Purpur — Paper fork with extra gameplay configuration, fetched from PurpurMC.",
    docsUrl: "https://purpurmc.org",
    tag: "v1",
    requirements: { engine: "process", arch: ["amd64", "arm64"], hostOs: ["linux", "windows"] },
    resolvers: [{ id: "purpur", kind: "purpur-v2", project: "purpur" }],
    versions: {},
    image: "ghcr.io/renom/java:21",
    install: [
      { op: "fetch-purpur", version: "{mcVersion}" },
      { op: "eula-accept" },
      {
        op: "writefile",
        path: "server.properties",
        contentTemplate:
          "motd={MOTD}\nserver-port={allocation.port}\nenforce-secure-profile=false\n",
      },
    ],
    run: {
      command: ["java", "-Xms{initMemory}M", "-Xmx{maxMemory}M", "-jar", "purpur.jar", "nogui"],
      workdir: "/data",
      stop: { kind: "console", command: "stop", timeoutSec: 30 },
      envCanon: {},
    },
    variables: [
      {
        key: "mcVersion",
        label: "Minecraft version",
        type: "string",
        default: "latest",
        userViewable: true,
        userEditable: true,
        internal: false,
      },
      {
        key: "MOTD",
        label: "Message of the day",
        type: "string",
        default: "A Renom server",
        userViewable: true,
        userEditable: true,
        internal: false,
        rules: { maxLength: 64 },
      },
      {
        key: "maxMemory",
        label: "Max RAM (MB)",
        type: "integer",
        default: 2048,
        userViewable: true,
        userEditable: true,
        internal: false,
        rules: { min: 512, max: 32768 },
      },
      {
        key: "initMemory",
        label: "Initial RAM (MB)",
        type: "integer",
        default: 1024,
        userViewable: false,
        userEditable: false,
        internal: true,
        rules: { min: 512 },
      },
    ],
    ports: [{ name: "game", protocol: "tcp", default: 25565, required: true }],
    healthcheck: { kind: "tcp", port: "game", timeoutSec: 10, startPeriodSec: 90 },
    backupPolicy: { consistency: "stopped" },
    update: { strategy: "resolver-refetch", onStart: true },
    fileDenylist: [".renom/**"],
    features: ["eula"],
  },
  {
    schemaVersion: 1,
    slug: "fabric",
    name: "Fabric",
    category: "minecraft-java",
    description: "Fabric mod loader. Boots under Docker; local installs wire up next.",
    docsUrl: "https://fabricmc.net",
    tag: "v1",
    requirements: { engine: "docker", arch: ["amd64", "arm64"], hostOs: ["linux"] },
    resolvers: [{ id: "fabric-meta", kind: "fabric-meta" }],
    versions: {},
    image: "ghcr.io/renom/java:21",
    install: [{ op: "fetch-fabric", mcVersion: "{mcVersion}" }],
    run: {
      command: [
        "java",
        "-Xms{initMemory}M",
        "-Xmx{maxMemory}M",
        "-jar",
        "fabric-server-launch.jar",
        "nogui",
      ],
      workdir: "/data",
      stop: { kind: "console", command: "stop", timeoutSec: 30 },
      envCanon: {},
    },
    variables: [
      {
        key: "mcVersion",
        label: "Minecraft version",
        type: "string",
        default: "latest",
        userViewable: true,
        userEditable: true,
        internal: false,
      },
      {
        key: "maxMemory",
        label: "Max RAM (MB)",
        type: "integer",
        default: 2048,
        userViewable: true,
        userEditable: true,
        internal: false,
        rules: { min: 512, max: 32768 },
      },
      {
        key: "initMemory",
        label: "Initial RAM (MB)",
        type: "integer",
        default: 1024,
        userViewable: false,
        userEditable: false,
        internal: true,
        rules: { min: 512 },
      },
    ],
    ports: [{ name: "game", protocol: "tcp", default: 25565, required: true }],
    healthcheck: { kind: "tcp", port: "game", timeoutSec: 10, startPeriodSec: 90 },
    backupPolicy: { consistency: "stopped" },
    update: { strategy: "resolver-refetch", onStart: true },
    fileDenylist: [".renom/**"],
    features: ["eula"],
  },
  {
    schemaVersion: 1,
    slug: "forge",
    name: "Forge",
    category: "minecraft-java",
    description: "Minecraft Forge mod loader. Boots under Docker; local installs wire up next.",
    docsUrl: "https://minecraftforge.net",
    tag: "v1",
    requirements: { engine: "docker", arch: ["amd64", "arm64"], hostOs: ["linux"] },
    resolvers: [{ id: "forge", kind: "forge-promotions" }],
    versions: {},
    image: "ghcr.io/renom/java:21",
    install: [{ op: "fetch-forge", mcVersion: "{mcVersion}" }],
    run: {
      command: [
        "java",
        "-Xms{initMemory}M",
        "-Xmx{maxMemory}M",
        "@user_jvm_args.txt",
        "@libraries/net/minecraftforge/forge/{mcVersion}-forge-args.txt",
        "nogui",
      ],
      workdir: "/data",
      stop: { kind: "console", command: "stop", timeoutSec: 30 },
      envCanon: {},
    },
    variables: [
      {
        key: "mcVersion",
        label: "Minecraft version",
        type: "string",
        default: "latest",
        userViewable: true,
        userEditable: true,
        internal: false,
      },
      {
        key: "maxMemory",
        label: "Max RAM (MB)",
        type: "integer",
        default: 2048,
        userViewable: true,
        userEditable: true,
        internal: false,
        rules: { min: 512, max: 32768 },
      },
      {
        key: "initMemory",
        label: "Initial RAM (MB)",
        type: "integer",
        default: 1024,
        userViewable: false,
        userEditable: false,
        internal: true,
        rules: { min: 512 },
      },
    ],
    ports: [{ name: "game", protocol: "tcp", default: 25565, required: true }],
    healthcheck: { kind: "tcp", port: "game", timeoutSec: 10, startPeriodSec: 90 },
    backupPolicy: { consistency: "stopped" },
    update: { strategy: "resolver-refetch", onStart: true },
    fileDenylist: [".renom/**"],
    features: ["eula"],
  },
  {
    schemaVersion: 1,
    slug: "velocity",
    name: "Velocity",
    category: "proxy",
    description: "Velocity proxy (Java). Boots under Docker; local installs wire up next.",
    docsUrl: "https://velocitypowered.com",
    tag: "v1",
    requirements: { engine: "docker", arch: ["amd64", "arm64"], hostOs: ["linux"] },
    resolvers: [],
    versions: {},
    image: "ghcr.io/renom/java:21",
    install: [{ op: "fetch-velocity", version: "{mcVersion}" }],
    run: {
      command: ["java", "-Xms{initMemory}M", "-Xmx{maxMemory}M", "-jar", "velocity.jar"],
      workdir: "/data",
      stop: { kind: "console", command: "end", timeoutSec: 30 },
      envCanon: {},
    },
    variables: [
      {
        key: "mcVersion",
        label: "Proxy version",
        type: "string",
        default: "latest",
        userViewable: true,
        userEditable: true,
        internal: false,
      },
      {
        key: "maxMemory",
        label: "Max RAM (MB)",
        type: "integer",
        default: 512,
        userViewable: true,
        userEditable: true,
        internal: false,
        rules: { min: 256, max: 8192 },
      },
      {
        key: "initMemory",
        label: "Initial RAM (MB)",
        type: "integer",
        default: 256,
        userViewable: false,
        userEditable: false,
        internal: true,
        rules: { min: 128 },
      },
    ],
    ports: [{ name: "proxy", protocol: "tcp", default: 25577, required: true }],
    healthcheck: { kind: "none", timeoutSec: 10, startPeriodSec: 90 },
    backupPolicy: { consistency: "best-effort" },
    update: { strategy: "none", onStart: false },
    fileDenylist: [".renom/**"],
    features: [],
  },
];

/** A tiny static resolver used by tests and offline installs (never network-dependent). */
export const STATIC_TEST_VERSIONS = ["1.21.1", "1.21.8", "1.26.2"];
